defaults: &defaults
  adapter: mysql2
  username: gamenight
  password: 
  host: localhost

production:
  <<: *defaults
  database: gamenight_dev

development:
  <<: *defaults
  database: gamenight_dev

test:
  <<: *defaults
  database: gamenight_test
