defaults: &defaults
  adapter: mysql
  username: tinder
  password: 
  host: localhost

production:
  <<: *defaults
  database: tinder_dev

development:
  <<: *defaults
  database: tinder_dev

test:
  <<: *defaults
  database: tinder_test
